### ISSUE TITLE
Add key to note wrapper decorations

### ISSUE THREAD

**Issue by RichieAHB** [guardian/prosemirror-noting#13]
After experiencing some slow down with large documents and looking at some flame charts for large documents with notes throughout, it looks like the note wrappers (widget decos at each end) could benefit from being keyed!

**Comment by jonathonherbert** [comment]
Resolved by #14.

**Comment by RichieAHB** [comment]
@jonathonherbert In case it ever becomes a dire priority I once wrote a new plugin that re-modelled notes as one single plugin and seems to work perfectly across undo / or as many different layers of note types as you could image: https://github.com/RichieAHB/prosemirror-ranges. It uses Rails (a span of notes that can have a variety different types that merge / slice each other, e.g. flag and correct on one rail, and notes on another), Ranges (the spans of marks on each rail) and a coordinating RailSet that manages the cursor position between all of these, the state of a placeholder (a note of zero width) etc.

It has **no** documentation, but does have an example to play with in the repo. No obligation to use it but if you were ever interested then I'd happily run you through it one time, even if it's just a good conversation to consider how best to start noting again with a better documented codebase or improve the existing version.

The only thing it's missing (I think) is storing metadata on the notes, which should be pretty easy to add.

No compulsion at all, but seeing this just reminded me I had it and thought I'd fire it over!

**Comment by jonathonherbert** [comment]
Thanks for mentioning this @RichieAHB – I remember you discussing a while back!

I'll take a look – apart from the usual browser-specific troubles with widget decorations and cursor positions, the plugin is quite stable at the moment, but not easy to maintain. If there's a significant push to add new functionality or address the edge cases we know exist, it might well be worth looking at a rewrite.
