### ISSUE TITLE
Yarn is installing an older version

### ISSUE THREAD

**Issue by MrAtiebatie** [guardian/prosemirror-noting#22]
`yarn add prosemirror-noting` is adding an older version of this plugin. I thought yarn would work as well since there is a yarn.lock file in the repo.

Could you update this?

**Comment by jonathonherbert** [comment]
Thanks for mentioning, @MrAtiebatie – this was likely caused my a mistaken publish, which had to be removed. We've just released 3.1.4 – does a `yarn add` now work as expected?

**Comment by techpeace** [comment]
This is due to not prefixing with the `@guardian` namespace on install:

`yarn add @guardian/prosemirror-noting`

I'll submit a PR to the `README` to update this.

**Comment by jonathonherbert** [comment]
Well spotted, @techpeace! Thanks for the PR.
