### ISSUE TITLE
The demo link in the readme 404s

### ISSUE THREAD

**Issue by chanced** [guardian/prosemirror-noting#31]
The basic demo link in the readme points to https://guardian.github.com/prosemirror-noting which is 404ing on my end.

**Comment by swapnil233** [comment]
Any update on this? I'd like to look at the example as well

**Comment by paperboyo** [comment]
Hi. Found [this](https://github.com/guardian/prosemirror-noting/pull/34). And the link there works:
https://guardian.github.io/prosemirror-noting/

We should probably merge #34? cc @alinaboghiu
